// Auto-generated build information
// Generated: 2025-11-21 01:00:25
// DO NOT EDIT - This file is automatically generated during compilation

#ifndef BUILD_INFO_H
#define BUILD_INFO_H

// Software version (from Device_Config.h)
#define BUILD_VERSION "3.0.0-RC.9"

// Git information
#define BUILD_GIT_COMMIT "9f10899+"
#define BUILD_GIT_BRANCH "v3_RC"

// Build number (MD5 hash of source files, last 6 chars)
#define BUILD_NUMBER "a34bd6"

// Build timestamp
#define BUILD_TIMESTAMP "2025-11-21 01:00:25"
#define BUILD_DATE "2025-11-21"

// Full version string with build info
#define BUILD_FULL_VERSION "3.0.0-RC.9 (a34bd6)"

// Detailed build string for debugging
#define BUILD_INFO_STRING "3.0.0-RC.9 build:a34bd6 git:9f10899+ 2025-11-21"

#endif // BUILD_INFO_H
