// Auto-generated build information
// Generated: 2025-11-21 00:55:23
// DO NOT EDIT - This file is automatically generated during compilation

#ifndef BUILD_INFO_H
#define BUILD_INFO_H

// Software version (from Device_Config.h)
#define BUILD_VERSION "3.0.0-RC.9"

// Git information
#define BUILD_GIT_COMMIT "8a8f1e9+"
#define BUILD_GIT_BRANCH "v3_RC"

// Build number (MD5 hash of source files, last 6 chars)
#define BUILD_NUMBER "624ba5"

// Build timestamp
#define BUILD_TIMESTAMP "2025-11-21 00:55:23"
#define BUILD_DATE "2025-11-21"

// Full version string with build info
#define BUILD_FULL_VERSION "3.0.0-RC.9 (624ba5)"

// Detailed build string for debugging
#define BUILD_INFO_STRING "3.0.0-RC.9 build:624ba5 git:8a8f1e9+ 2025-11-21"

#endif // BUILD_INFO_H
