// Auto-generated build information
// Generated: 2025-11-21 12:11:49
// DO NOT EDIT - This file is automatically generated during compilation

#ifndef BUILD_INFO_H
#define BUILD_INFO_H

// Software version (from Device_Config.h)
#define BUILD_VERSION "3.0.0-RC.9"

// Git information
#define BUILD_GIT_COMMIT "b9ba6e7+"
#define BUILD_GIT_BRANCH "v3_RC"

// Build number (MD5 hash of source files, last 6 chars)
#define BUILD_NUMBER "182229"

// Build timestamp
#define BUILD_TIMESTAMP "2025-11-21 12:11:49"
#define BUILD_DATE "2025-11-21"

// Full version string with build info
#define BUILD_FULL_VERSION "3.0.0-RC.9 (182229)"

// Detailed build string for debugging
#define BUILD_INFO_STRING "3.0.0-RC.9 build:182229 git:b9ba6e7+ 2025-11-21"

#endif // BUILD_INFO_H
